### ISSUE TITLE
Need explanation about your experiments

### ISSUE THREAD

**Issue by bonlime** [NVlabs/AFNO-transformer#1]
Hi, first of all thanks for a very interesting paper.
Could you clarify in more details the results in table 6. `AFNO [Non-Adaptive Weights]`? 
What you mean by `Adaptive weights`? No MLP? I can see in this repo exist a [BFNO module](https://github.com/NVlabs/AFNO-transformer/blob/master/afno/bfno2d.py) was it used in this experiment?

**Comment by MortezaMardani** [comment]
non-adaptive refers to BFNO with only one block i.e., B=1. it's essentially FNO.

**Comment by ZQ-perfect** [comment]
sorry, I want to know how to import the datasets into the code ?
